name: .NET

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish GhostCursor
        uses: GerardSmit/publish-nuget@v3.1.2
        with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: Directory.Build.props
          PROJECT_FILE_PATH: |
            src/GhostCursor/GhostCursor.csproj
            src/GhostCursor.CefSharp/GhostCursor.CefSharp.csproj
            src/GhostCursor.CefSharp/GhostCursor.CefSharp.NETCore.csproj
            src/GhostCursor.CefSharp.WinForms/GhostCursor.CefSharp.WinForms.csproj
            src/GhostCursor.CefSharp.WinForms/GhostCursor.CefSharp.WinForms.NETCore.csproj
      